#!/bin/bash
ruby -I../lib/ ../SNES_Utils/bin/png2snes -f assets/tileset.png -b 4 -a 0x0000

ruby -I../SNES_Utils/lib ../SNES_Utils/bin/vas -f tilemap.asm

cp out.smc  /mnt/c/Users/vbihl/Desktop/tilemap.smc
