#!/bin/bash
ruby -I../SNES_Utils/lib/ ../SNES_Utils/bin/png2snes -f assets/tileset.png -b 4 -a 0x0000
ruby -I../SNES_Utils/lib/ ../SNES_Utils/bin/png2snes -f assets/red.png -b 4
ruby -I../SNES_Utils/lib/ ../SNES_Utils/bin/png2snes -f assets/pkmn.png -b 4 -a 0x0000

ruby -I../SNES_Utils/lib ../SNES_Utils/bin/vas -f main.asm

cp out.smc /mnt/c/Users/vivie/Desktop/tilemap.smc
